import { Product, Category, Review } from "./types";

export const categories: Category[] = [
  { id: "1", name: "Scripts", slug: "scripts", icon: "code", count: 24 },
  { id: "2", name: "Models", slug: "models", icon: "box", count: 18 },
  { id: "3", name: "UI Systems", slug: "ui-systems", icon: "layout", count: 12 },
  { id: "4", name: "Admin Systems", slug: "admin-systems", icon: "shield", count: 8 },
  { id: "5", name: "Vehicles", slug: "vehicles", icon: "car", count: 15 },
  { id: "6", name: "Building Systems", slug: "building-systems", icon: "building", count: 7 },
  { id: "7", name: "Donation Systems", slug: "donation-systems", icon: "heart", count: 9 },
  { id: "8", name: "Custom Orders", slug: "custom-orders", icon: "settings", count: 5 },
  { id: "9", name: "Product Marketplace", slug: "marketplace", icon: "store", count: 99 },
];

export const products: Product[] = [
  {
    id: "1",
    title: "Advanced Admin System",
    slug: "advanced-admin-system",
    description: "Complete admin panel with ranks, permissions, moderation tools, and customizable commands.",
    price: 24.99,
    originalPrice: 39.99,
    category: "Admin Systems",
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    rating: 4.9,
    reviewsCount: 128,
    salesCount: 1542,
    features: ["Rank management", "Permission system", "Moderation tools", "Custom commands", "Ban/Kick/Mute", "Logging system"],
    compatibility: ["Roblox Studio", "Luau", "Any Place"],
    installationGuide: "Download the script, insert into ServerScriptService, and configure the settings module.",
    createdAt: "2025-01-15",
    updatedAt: "2026-03-20",
    featured: true,
    popular: true,
  },
  {
    id: "2",
    title: "Premium Vehicle System",
    slug: "premium-vehicle-system",
    description: "Realistic vehicle physics with car customization, fuel system, and multiplayer support.",
    price: 34.99,
    category: "Vehicles",
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    rating: 4.8,
    reviewsCount: 96,
    salesCount: 893,
    features: ["Realistic physics", "Car customization", "Fuel system", "Multiplayer sync", "Speed boost", "Drift mechanics"],
    compatibility: ["Roblox Studio", "Luau", "VehicleSeats"],
    installationGuide: "Import the model, place in workspace, and configure vehicle properties.",
    createdAt: "2025-03-20",
    updatedAt: "2026-02-15",
    featured: true,
    popular: true,
  },
  {
    id: "3",
    title: "Modern UI Library",
    slug: "modern-ui-library",
    description: "Collection of 200+ modern UI components, animations, and templates for your Roblox games.",
    price: 19.99,
    originalPrice: 29.99,
    category: "UI Systems",
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    rating: 4.7,
    reviewsCount: 215,
    salesCount: 2105,
    features: ["200+ components", "Dark/Light themes", "Animations", "Mobile responsive", "Easy customization", "Documentation"],
    compatibility: ["Roblox Studio", "Luau", "ScreenGuis"],
    installationGuide: "Insert the UI Library into StarterGui and require the module in your scripts.",
    createdAt: "2025-06-10",
    updatedAt: "2026-04-01",
    featured: true,
    popular: true,
  },
  {
    id: "4",
    title: "Donation & VIP System",
    slug: "donation-vip-system",
    description: "Complete donation system with tiers, perks, payment processing, and automatic rank assignment.",
    price: 29.99,
    category: "Donation Systems",
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    rating: 4.6,
    reviewsCount: 73,
    salesCount: 654,
    features: ["Donation tiers", "VIP perks", "Auto rank assignment", "Payment processing", "Discord integration", "Webhook support"],
    compatibility: ["Roblox Studio", "Luau", "Datastores"],
    installationGuide: "Configure the module with your group ID and donation settings, then insert into ServerScriptService.",
    createdAt: "2025-08-05",
    updatedAt: "2026-01-20",
    featured: true,
    popular: false,
  },
  {
    id: "5",
    title: "Building System Pro",
    slug: "building-system-pro",
    description: "Advanced building system with grid placement, rotation, snapping, and undo/redo functionality.",
    price: 39.99,
    category: "Building Systems",
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    rating: 4.8,
    reviewsCount: 54,
    salesCount: 432,
    features: ["Grid placement", "Rotation system", "Snapping", "Undo/Redo", "Save/Load builds", "Multiplayer sync"],
    compatibility: ["Roblox Studio", "Luau", "PhysicsService"],
    installationGuide: "Place the BuildingSystem folder into ServerScriptService and configure the settings.",
    createdAt: "2025-10-01",
    updatedAt: "2026-03-10",
    featured: false,
    popular: false,
  },
  {
    id: "6",
    title: "Orbital Hub – Admin GUI",
    slug: "orbital-hub-admin-gui",
    description: "Sleek, modern admin GUI with gesture controls, particle effects, and real-time server monitoring.",
    price: 44.99,
    originalPrice: 59.99,
    category: "Admin Systems",
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    rating: 4.9,
    reviewsCount: 167,
    salesCount: 2100,
    features: ["Gesture controls", "Particle effects", "Server monitoring", "Player management", "Script execution", "Custom themes"],
    compatibility: ["Roblox Studio", "Luau", "All Platforms"],
    installationGuide: "Insert into StarterGui, run the setup script, and configure via the settings panel.",
    createdAt: "2025-11-20",
    updatedAt: "2026-04-05",
    featured: true,
    popular: true,
  },
  {
    id: "7",
    title: "Realistic Weapon System",
    slug: "realistic-weapon-system",
    description: "High-quality weapon system with recoil, scoping, attachments, and damage models.",
    price: 27.99,
    category: "Scripts",
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    rating: 4.7,
    reviewsCount: 89,
    salesCount: 1100,
    features: ["Recoil system", "Scoping", "Weapon attachments", "Damage models", "Ammo system", "Animation support"],
    compatibility: ["Roblox Studio", "Luau", "Tool system"],
    installationGuide: "Import weapon models, insert scripts into Tools, and configure weapon stats.",
    createdAt: "2025-04-15",
    updatedAt: "2026-02-28",
    featured: false,
    popular: true,
  },
  {
    id: "8",
    title: "Neon UI Pack",
    slug: "neon-ui-pack",
    description: "Cyberpunk-themed UI pack with neon gradients, animated borders, and holographic effects.",
    price: 14.99,
    category: "UI Systems",
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    rating: 4.5,
    reviewsCount: 142,
    salesCount: 1800,
    features: ["Neon gradients", "Animated borders", "Holographic effects", "Cyberpunk theme", "50+ screens", "Figma source"],
    compatibility: ["Roblox Studio", "Luau", "ScreenGuis"],
    installationGuide: "Insert the NeonUI folder into StarterGui and import the main module.",
    createdAt: "2025-12-01",
    updatedAt: "2026-03-25",
    featured: false,
    popular: false,
  },
  {
    id: "9",
    title: "3D Character Models Pack",
    slug: "3d-character-models-pack",
    description: "50+ high-quality 3D character models with rigs, animations, and texture files.",
    price: 49.99,
    originalPrice: 79.99,
    category: "Models",
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    rating: 4.6,
    reviewsCount: 67,
    salesCount: 523,
    features: ["50+ characters", "Rigged", "Animations included", "Texture files", "LOD support", "Optimized"],
    compatibility: ["Roblox Studio", "Blender", "FBX format"],
    installationGuide: "Import the RBXM files into Roblox Studio or use the FBX files in external software.",
    createdAt: "2025-07-20",
    updatedAt: "2026-01-10",
    featured: false,
    popular: false,
  },
  {
    id: "10",
    title: "Economy System Plus",
    slug: "economy-system-plus",
    description: "Full-featured economy system with currency, shops, trading, and leaderboards.",
    price: 22.99,
    category: "Scripts",
    image: "/placeholder.svg",
    images: ["/placeholder.svg", "/placeholder.svg", "/placeholder.svg"],
    rating: 4.6,
    reviewsCount: 54,
    salesCount: 720,
    features: ["Currency system", "Shops", "Trading", "Leaderboards", "Daily rewards", "Data persistence"],
    compatibility: ["Roblox Studio", "Luau", "Datastores"],
    installationGuide: "Insert the Economy folder into ServerScriptService and configure the settings module.",
    createdAt: "2025-09-10",
    updatedAt: "2026-03-01",
    featured: false,
    popular: false,
  },
];

export const reviews: Review[] = [
  {
    id: "1",
    productId: "1",
    userId: "u1",
    username: "FrostyDev",
    avatar: "/placeholder.svg",
    rating: 5,
    text: "Best admin system I've ever used. The customization options are endless and the support is amazing!",
    verified: true,
    createdAt: "2026-03-15",
  },
  {
    id: "2",
    productId: "1",
    userId: "u2",
    username: "GameBuilderPro",
    avatar: "/placeholder.svg",
    rating: 5,
    text: "Incredible quality. My players love the new admin commands. Highly recommended!",
    verified: true,
    createdAt: "2026-03-10",
  },
  {
    id: "3",
    productId: "2",
    userId: "u3",
    username: "VroomMaster",
    avatar: "/placeholder.svg",
    rating: 4,
    text: "Great vehicle system! The physics are really smooth. Would love to see more car models included.",
    verified: true,
    createdAt: "2026-02-20",
  },
  {
    id: "4",
    productId: "3",
    userId: "u4",
    username: "UXDesigner",
    avatar: "/placeholder.svg",
    rating: 5,
    text: "This UI library saved me weeks of work. Every component is clean and well-documented.",
    verified: true,
    createdAt: "2026-04-01",
  },
  {
    id: "5",
    productId: "6",
    userId: "u5",
    username: "ScriptMaster",
    avatar: "/placeholder.svg",
    rating: 5,
    text: "Orbital Hub is on another level. The gesture controls are revolutionary for admin GUIs.",
    verified: true,
    createdAt: "2026-03-28",
  },
];

export const stats = {
  productsSold: 12500,
  activeCustomers: 3400,
  yearsExperience: 5,
  customerSatisfaction: 98,
};
